//! Autogenerated weights for $name_kebab_case$
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 3.0.0
//! DATE: 2021-02-19, STEPS: [10, ], REPEAT: 5, LOW RANGE: [], HIGH RANGE: []
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 128

// Executed Command:
// ../../../target/release/nuchain
// benchmark
// --chain=dev
// --steps=10
// --repeat=5
// --pallet=$name_kebab_case$
// --extrinsic=*
// --execution=wasm
// --wasm-execution=compiled
// --heap-pages=4096
// --output=../../../frame/$name_kebab_case$/src/weights.rs
// --template=../../../.maintain/frame-weight-template.hbs


#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for $name_kebab_case$.
pub trait WeightInfo {
        fn $param.method1_snake_case$() -> Weight;
        fn $param.method2_snake_case$() -> Weight;
}

/// Weights for $name_kebab_case$ using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
        fn $param.method1_snake_case$() -> Weight {
                (55_500_000 as Weight)
                        .saturating_add(T::DbWeight::get().reads(1 as Weight))
                        .saturating_add(T::DbWeight::get().writes(1 as Weight))
        }
        fn $param.method2_snake_case$() -> Weight {
                (53_200_000 as Weight)
                        .saturating_add(T::DbWeight::get().reads(1 as Weight))
                        .saturating_add(T::DbWeight::get().writes(1 as Weight))
        }
}

// For backwards compatibility and tests
impl WeightInfo for () {
        fn $param.method1_snake_case$() -> Weight {
                (55_500_000 as Weight)
                        .saturating_add(RocksDbWeight::get().reads(1 as Weight))
                        .saturating_add(RocksDbWeight::get().writes(1 as Weight))
        }
        fn $param.method2_snake_case$() -> Weight {
                (53_200_000 as Weight)
                        .saturating_add(RocksDbWeight::get().reads(1 as Weight))
                        .saturating_add(RocksDbWeight::get().writes(1 as Weight))
        }
}
